name: vlc_remote
description: VLC remote control

# Prevent accidentally publishing to pub.dev using `pub publish`
publish_to: 'none'

version: 1.4.1+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.9
  http: ^0.12.2
  just_throttle_it: ^1.0.0
  ping_discover_network: ^0.2.0+1
  shared_preferences: ^0.5.8
  transparent_image: ^1.0.0
  xml: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon-512.png
    - assets/cone.png
    - assets/linux-ifconfig.png
    - assets/linux-lua.png
    - assets/linux-main-interface.png
    - assets/linux-menu.png
    - assets/linux-password.png
    - assets/linux-show-settings.png
    - assets/linux-terminal.png
    - assets/linux-web.png
    - assets/mac-http-interface.png
    - assets/mac-ip.png
    - assets/mac-menu.png
    - assets/mac-network.png
    - assets/signal-0.png
    - assets/signal-1.png
    - assets/signal-2.png
    - assets/signal-3.png
    - assets/windows-cmd.png
    - assets/windows-ipconfig.png
    - assets/windows-lua.png
    - assets/windows-main-interface.png
    - assets/windows-menu.png
    - assets/windows-password.png
    - assets/windows-run.png
    - assets/windows-show-settings.png
    - assets/windows-web.png
